#!/usr/bin/env bun
/**
 * The screenshots in the README, taken rather than drawn.
 *
 *   bun run scripts/screenshots.ts
 *
 * A picture of a tool goes stale the moment the tool changes, and a stale one
 * is worse than none: it is a claim about what the thing looks like that
 * nobody checked. So they are regenerated by a script, from a running dev
 * server, and the script is the record of what each one is meant to show.
 *
 * It drives headless Chrome over the DevTools protocol — no browser-automation
 * dependency, because Chrome is already on any machine that can look at the
 * output, and the protocol is JSON over a WebSocket that Bun speaks natively.
 *
 * Each shot is set up by clicking what a person would click. Reaching into the
 * store instead would let a screenshot show a state the interface cannot
 * actually reach.
 */

import { mkdir, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1");
const OUT = join(ROOT, "docs", "images");
export const URL_BASE = process.env.TENSORCAD_URL ?? "http://localhost:5173";
const WIDTH = 1440;
const HEIGHT = 900;
export const PORT = 9333;

export const CHROME = [
  "C:/Program Files/Google/Chrome/Application/chrome.exe",
  "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe",
  "/usr/bin/google-chrome",
  "/usr/bin/chromium",
  "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
];

/** A small DevTools protocol client: send a method, await its reply. */
export class Devtools {
  private next = 1;
  private pending = new Map<number, { ok: (v: unknown) => void; no: (e: Error) => void }>();
  private listeners = new Map<string, ((params: any) => void)[]>();

  private constructor(private socket: WebSocket) {
    socket.addEventListener("message", (event) => {
      const message = JSON.parse(String(event.data)) as {
        id?: number;
        method?: string;
        params?: unknown;
        result?: unknown;
        error?: { message: string };
      };
      if (message.id === undefined) {
        for (const fn of this.listeners.get(message.method ?? "") ?? []) fn(message.params);
        return;
      }
      const waiter = this.pending.get(message.id);
      if (!waiter) return;
      this.pending.delete(message.id);
      if (message.error) waiter.no(new Error(message.error.message));
      else waiter.ok(message.result);
    });
  }

  static async connect(url: string): Promise<Devtools> {
    const socket = new WebSocket(url);
    await new Promise<void>((ok, no) => {
      socket.addEventListener("open", () => ok(), { once: true });
      socket.addEventListener("error", () => no(new Error("could not reach Chrome")), {
        once: true,
      });
    });
    return new Devtools(socket);
  }

  /** Be told about a protocol event, such as `Runtime.exceptionThrown`. */
  on(method: string, fn: (params: any) => void): void {
    this.listeners.set(method, [...(this.listeners.get(method) ?? []), fn]);
  }

  send<T = Record<string, unknown>>(method: string, params: unknown = {}): Promise<T> {
    const id = this.next++;
    this.socket.send(JSON.stringify({ id, method, params }));
    return new Promise<T>((ok, no) => {
      this.pending.set(id, { ok: ok as (v: unknown) => void, no });
      setTimeout(() => {
        if (this.pending.delete(id)) no(new Error(`${method} did not answer`));
      }, 60_000);
    });
  }

  /** Run an expression in the page and hand back what it evaluated to. */
  async eval<T>(expression: string): Promise<T> {
    const result = await this.send<{
      result: { value: T };
      exceptionDetails?: { text: string; exception?: { description?: string } };
    }>("Runtime.evaluate", { expression, awaitPromise: true, returnByValue: true });
    if (result.exceptionDetails) {
      throw new Error(result.exceptionDetails.exception?.description ?? result.exceptionDetails.text);
    }
    return result.result.value;
  }

  close(): void {
    this.socket.close();
  }
}

export const wait = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms));

/**
 * What the page does before each shot, written as things a person clicks.
 *
 * `settle` is generous on purpose: the engine is WebAssembly, the canvas
 * auto-fits after React Flow has measured every node, and a screenshot taken
 * mid-layout is a screenshot of nothing.
 */
const SETUP = `
window.__shot = {
  click(text, selector = "button, [role=menuitem], [role=tab], [role=option]") {
    const el = [...document.querySelectorAll(selector)].find(
      (e) => (e.textContent || "").trim() === text,
    );
    if (!el) throw new Error("nothing to click called " + JSON.stringify(text));
    el.click();
    return true;
  },
  // The detail control unfolds the drawing, and a fresh profile does not always
  // start flat.
  detail(levels) {
    const button = (label) =>
      [...document.querySelectorAll("button")].find(
        (b) => b.getAttribute("aria-label") === label,
      );
    for (let i = 0; i < 6; i++) {
      const out = button("Close one level");
      if (!out || out.disabled) break;
      out.click();
    }
    for (let i = 0; i < levels; i++) button("Open one more level")?.click();
  },
  // Where a named element is, so a shot can be framed on it rather than on the
  // whole window.
  box(selector) {
    const el = document.querySelector(selector);
    if (!el) throw new Error("nothing on screen matching " + selector);
    const r = el.getBoundingClientRect();
    return { x: r.x, y: r.y, width: r.width, height: r.height, scale: 1 };
  },
  // Frame the tabbed pane in the right column, from its tab strip down to the
  // status bar. The readout above it is in every shot already; what differs is
  // what is under the tabs.
  panelBox(rowSelector) {
    const panel = document.querySelector(".panel--edit").getBoundingClientRect();
    const column = document.querySelector(".app__right").getBoundingClientRect();
    let bottom = Math.min(panel.bottom, window.innerHeight - 24);
    // End on a whole row rather than through one. A list cut across an entry
    // reads as a rendering fault; cut between them it reads as a list.
    if (rowSelector) {
      const whole = [...document.querySelectorAll(rowSelector)]
        .map((e) => e.getBoundingClientRect())
        .filter((r) => r.bottom <= bottom);
      if (whole.length > 0) bottom = whole[whole.length - 1].bottom + 8;
    }
    return { x: column.x, y: panel.y, width: column.width, height: bottom - panel.y, scale: 1 };
  },
  // Give that pane more of the column, by dragging the divider above it. The
  // ladder's table does not fit in a third of the height, and a screenshot that
  // cuts off the thing it is about is not a screenshot of it.
  growPanel(by) {
    const bar = document.querySelector(".resizer--y");
    if (!bar) return;
    const r = bar.getBoundingClientRect();
    const at = (type, y) =>
      bar.dispatchEvent(
        new PointerEvent(type, { bubbles: true, clientX: r.x + 2, clientY: y, pointerId: 1 }),
      );
    bar.setPointerCapture = () => {};
    bar.releasePointerCapture = () => {};
    at("pointerdown", r.y);
    for (let step = 20; step <= by; step += 20) {
      window.dispatchEvent(
        new PointerEvent("pointermove", { bubbles: true, clientX: r.x + 2, clientY: r.y - step, pointerId: 1 }),
      );
    }
    window.dispatchEvent(new PointerEvent("pointerup", { bubbles: true, pointerId: 1 }));
  },
  // The volume view opens with the whole stack in frame, which from a distance
  // is mostly empty. It zooms on the wheel, like the canvas.
  zoom(steps) {
    const canvas = document.querySelector(".app__center canvas");
    if (!canvas) return;
    const r = canvas.getBoundingClientRect();
    for (let i = 0; i < steps; i++) {
      canvas.dispatchEvent(
        new WheelEvent("wheel", {
          bubbles: true, cancelable: true, deltaY: -120,
          clientX: r.x + r.width / 2, clientY: r.y + r.height / 2,
        }),
      );
    }
  },
};
"ready"
`;

interface Shot {
  name: string;
  caption: string;
  /** Run in the page, after the app has loaded. */
  prepare?: string;
  /**
   * An expression returning the rectangle to frame the shot on. Without one it
   * is the whole window, which is right for the first image and wasteful for
   * the rest: four pictures of the same window differing in one panel say less
   * than one picture of each panel.
   */
  clip?: string;
  settle?: number;
}

const SHOTS: Shot[] = [
  {
    name: "editor",
    caption: "The sheet: blocks with typed pins, a shape on every net, and the readout beside it.",
    // One level open, so the drawing shows both the stack and what is inside it.
    prepare: `window.__shot.detail(1); "ok"`,
    settle: 3000,
  },
  {
    name: "cluster",
    caption: "Every way of splitting the training across the cluster, and which of them fit.",
    // Training first, and a moment for it to draw the switch the view is on.
    prepare: `(async () => {
      window.__shot.detail(0);
      window.__shot.growPanel(260);
      window.__shot.click("Training");
      await new Promise((r) => setTimeout(r, 400));
      window.__shot.click("Cluster");
      return "ok";
    })()`,
    clip: `window.__shot.panelBox(".plan")`,
    settle: 3000,
  },
  {
    name: "ladder",
    caption: "The width ladder: the same design at several widths, and what to scale by at each.",
    prepare: `(async () => {
      window.__shot.detail(0);
      window.__shot.growPanel(260);
      window.__shot.click("Training");
      await new Promise((r) => setTimeout(r, 400));
      window.__shot.click("Width ladder");
      return "ok";
    })()`,
    clip: `window.__shot.panelBox(".rung, .mup__class")`,
    settle: 3000,
  },
  {
    name: "volume",
    caption: "The volume view, a port of Brendan Bycroft's LLM visualisation.",
    // An async wrapper, because `Runtime.evaluate` runs a script rather than a
    // module and a bare `await` is a syntax error there.
    prepare: `(async () => {
      window.__shot.click("3D");
      await new Promise((r) => setTimeout(r, 2500));
      window.__shot.zoom(6);
      return "ok";
    })()`,
    clip: `window.__shot.box(".app__center")`,
    settle: 5000,
  },
];

async function main(): Promise<void> {
  // Fail early and clearly rather than screenshotting a connection error.
  const reachable = await fetch(URL_BASE)
    .then((r) => r.ok)
    .catch(() => false);
  if (!reachable) {
    console.error(`Nothing is serving ${URL_BASE}. Start it with:\n  bun run --cwd packages/ui dev`);
    process.exit(1);
  }

  let chrome = "";
  for (const candidate of CHROME) {
    if (await Bun.file(candidate).exists()) {
      chrome = candidate;
      break;
    }
  }
  if (!chrome) {
    console.error("No Chrome found. Set one of:\n  " + CHROME.join("\n  "));
    process.exit(1);
  }

  const profile = join(ROOT, "dist", "chrome-profile");
  await rm(profile, { recursive: true, force: true });
  const browser = Bun.spawn(
    [
      chrome,
      "--headless=new",
      "--disable-gpu",
      "--no-sandbox",
      "--hide-scrollbars",
      "--force-color-profile=srgb",
      `--remote-debugging-port=${PORT}`,
      `--user-data-dir=${profile}`,
      `--window-size=${WIDTH},${HEIGHT}`,
      "about:blank",
    ],
    { stdout: "ignore", stderr: "ignore" },
  );

  try {
    // Chrome writes the port file before it accepts connections, so poll.
    let target: { webSocketDebuggerUrl: string } | undefined;
    for (let i = 0; i < 60 && !target; i++) {
      await wait(250);
      target = await fetch(`http://127.0.0.1:${PORT}/json/list`)
        .then((r) => r.json() as Promise<{ type: string; webSocketDebuggerUrl: string }[]>)
        .then((list) => list.find((t) => t.type === "page"))
        .catch(() => undefined);
    }
    if (!target) throw new Error("Chrome never opened its debugging port");

    const dt = await Devtools.connect(target.webSocketDebuggerUrl);
    await dt.send("Page.enable");
    await dt.send("Runtime.enable");
    await dt.send("Emulation.setDeviceMetricsOverride", {
      width: WIDTH,
      height: HEIGHT,
      deviceScaleFactor: 2, // Retina, so the images stay sharp when scaled down.
      mobile: false,
    });

    await mkdir(OUT, { recursive: true });
    // Llama-3-8B, opened the way anybody would open a design sent to them: from
    // a link carrying it. A preset picked from the dropdown would work too, but
    // it is a menu to drive, and the default design is too small to show what
    // the cluster and the ladder are for.
    const { getPreset, loadEngine } = await import("@tensor-cad/engine/node");
    await loadEngine();
    const design = Buffer.from(JSON.stringify(getPreset("llama-3-8b"))).toString("base64url");
    const start = `${URL_BASE}/#design=p${design}`;

    for (const shot of SHOTS) {
      // Through a blank page: a navigation that changes only the fragment does
      // not load the page again, and loading is when a link is read.
      await dt.send("Page.navigate", { url: "about:blank" });
      await wait(200);
      await dt.send("Page.navigate", { url: start });
      // The engine is WebAssembly and the canvas fits itself once React Flow
      // has measured every node; both happen after `load`.
      await wait(5000);
      await dt.eval(SETUP);
      if (shot.prepare) await dt.eval(shot.prepare);
      await wait(shot.settle ?? 2000);

      const clip = shot.clip
        ? await dt.eval<{ x: number; y: number; width: number; height: number; scale: number }>(
            shot.clip,
          )
        : undefined;
      const { data } = await dt.send<{ data: string }>("Page.captureScreenshot", {
        format: "png",
        captureBeyondViewport: false,
        ...(clip ? { clip } : {}),
      });
      const path = join(OUT, `${shot.name}.png`);
      await writeFile(path, Buffer.from(data, "base64"));
      const size = Bun.file(path).size;
      console.log(`  docs/images/${shot.name}.png  ${(size / 1024).toFixed(0)} KB  ${shot.caption}`);
    }
    dt.close();
  } finally {
    browser.kill();
    await rm(profile, { recursive: true, force: true }).catch(() => {});
  }
}

if (import.meta.main) await main();
