import { writeFileSync, mkdirSync } from "node:fs";
import { analyze, generateTorch, getPreset, loadEngine, validate } from "@tensor-cad/engine/node";
await loadEngine();
const doc = structuredClone(getPreset("nano-sort"));
doc.meta.name = "nano-diff";
for (const [k, v] of [["H", 2], ["dh", 12]] as const) (doc.symbols[k] as any).value = v;
(doc.symbols.Hkv as any).value = 2;
const block = doc.graph.nodes.find((n) => n.id === "layers")!.graph!.nodes.find((n) => n.id === "block")!;
block.params = { ...block.params, attention: "diff", rope: { theta: 10000 } };
const report = validate(doc, {});
console.log("findings", report.findings.filter((f: any) => f.severity !== "info").map((f: any) => f.rule + ": " + f.message));
mkdirSync("out/nano-diff", { recursive: true });
const g = generateTorch(doc);
console.log("warnings", g.warnings);
writeFileSync("out/nano-diff/model.py", g.files.find((f) => f.path === "model.py")!.contents);
writeFileSync("out/nano-diff/design.json", JSON.stringify(doc, null, 2));
const a = analyze(doc, { T: 11, B: 2 });
console.log("params", a.params.total, "unmasked", a.flops.fwdTotalUnmasked, "kv/token", a.kv.bytesPerToken);
