"""Command line entry point.

Every subcommand prints exactly one JSON object to stdout and human-readable
progress to stderr, so the TypeScript side can parse stdout without filtering.
"""

from __future__ import annotations

import argparse
import json
import sys
import traceback
from typing import Any

from . import __version__

TORCH_MISSING = "torch_missing"


def _progress(message: str) -> None:
    print(message, file=sys.stderr, flush=True)


def _emit(payload: dict[str, Any]) -> int:
    """Write the result object to stdout. Returns the process exit code."""
    json.dump(payload, sys.stdout, default=str)
    sys.stdout.write("\n")
    sys.stdout.flush()
    return 0 if payload.get("ok") else 1


def _fail(error: Exception, command: str) -> dict[str, Any]:
    kind = type(error).__name__
    payload: dict[str, Any] = {
        "ok": False,
        "command": command,
        "error": str(error),
        "error_kind": kind,
    }
    if isinstance(error, ImportError) and (error.name or "").split(".")[0] == "torch":
        payload["error_kind"] = TORCH_MISSING
        payload["error"] = (
            "PyTorch could not be imported. Install it from the index that matches your GPU, "
            "e.g. pip install torch --index-url https://download.pytorch.org/whl/cu128"
        )
        # An installed-but-broken torch lands here too, so keep the real reason.
        payload["import_error"] = str(error)
    _progress(f"{command} failed: {kind}: {error}")
    _progress(traceback.format_exc())
    return payload


def _require_torch() -> None:
    import torch  # noqa: F401


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="tensorcad-runtime",
        description="Verify and smoke-train PyTorch models generated by TensorCAD.",
    )
    parser.add_argument("--version", action="version", version=f"tensorcad-runtime {__version__}")
    subparsers = parser.add_subparsers(dest="command", required=True)

    # -- verify ------------------------------------------------------------
    verify = subparsers.add_parser(
        "verify", help="instantiate a generated model and cross-check it against its design"
    )
    verify.add_argument("model", help="path to a generated model.py")
    verify.add_argument("--batch", type=int, default=2, help="batch size for the forward pass")
    verify.add_argument("--seq", type=int, default=128, help="sequence length for the forward pass")
    verify.add_argument("--class-name", default=None, help="model class to instantiate")
    verify.add_argument(
        "--max-forward-bytes",
        type=int,
        default=None,
        help="skip the real forward pass above this fp32 weight size (default 2 GiB)",
    )
    verify.add_argument("--no-export", action="store_true", help="skip the torch.export check")
    verify.add_argument("--no-flops", action="store_true", help="skip FLOP counting")
    verify.add_argument(
        "--phase-timeout",
        type=float,
        default=None,
        help="seconds to spend tracing for FLOPs and for export before giving up (default 300)",
    )

    # -- smoke-train -------------------------------------------------------
    train = subparsers.add_parser("smoke-train", help="train a generated model briefly")
    train.add_argument("model", help="path to a generated model.py")
    train.add_argument("--steps", type=int, required=True, help="number of optimizer steps")
    train.add_argument("--seq", type=int, default=256, help="sequence length")
    train.add_argument("--batch", type=int, default=8, help="batch size")
    train.add_argument("--lr", type=float, default=3e-4, help="peak learning rate")
    train.add_argument("--out", default=None, help="run log path (default runs/<name>.jsonl)")
    train.add_argument("--data", default=None, help="prepared corpus directory or manifest")
    train.add_argument("--class-name", default=None, help="model class to instantiate")
    train.add_argument("--seed", type=int, default=1337, help="random seed")
    train.add_argument("--log-every", type=int, default=1, help="log every N steps")
    train.add_argument("--device", default=None, choices=["cuda", "cpu"], help="force a device")
    train.add_argument("--compile", action="store_true", help="wrap the model in torch.compile")
    train.add_argument("--weight-decay", type=float, default=0.1, help="AdamW weight decay")
    train.add_argument(
        "--init",
        default="gpt2",
        choices=["gpt2", "default"],
        help="weight init: 'gpt2' re-initializes N(0, 0.02) (default), "
        "'default' keeps PyTorch's defaults",
    )

    # -- trace -------------------------------------------------------------
    trace = subparsers.add_parser(
        "trace", help="run a tiny model on one input and record every value it computes"
    )
    trace.add_argument("model", help="path to a generated model.py, with its design beside it")
    trace.add_argument("--out", required=True, help="where to write the trace JSON")
    trace.add_argument(
        "--task",
        default="auto",
        choices=["auto", "sort", "untrained"],
        help="train it to sort first, or record it as initialised (default: sort when it can learn it)",
    )
    trace.add_argument("--positions", type=int, default=None, help="input length for an untrained trace")
    trace.add_argument("--max-params", type=int, default=1_000_000, help="refuse designs larger than this")
    trace.add_argument("--seed", type=int, default=1337, help="random seed")
    trace.add_argument("--max-steps", type=int, default=6000, help="give up training after this")
    trace.add_argument("--batch", type=int, default=64, help="batch size")
    trace.add_argument("--lr", type=float, default=5e-4, help="learning rate")
    trace.add_argument(
        "--input",
        default=None,
        help="the input as comma-separated token ids, e.g. 2,1,0,1,0,2 (default: seeded, or Bycroft's own example)",
    )

    # -- data --------------------------------------------------------------
    data = subparsers.add_parser("data", help="corpus preparation")
    data_sub = data.add_subparsers(dest="data_command", required=True)
    prepare = data_sub.add_parser("prepare", help="download and tokenize a small corpus")
    prepare.add_argument(
        "--dataset", default="tinystories", choices=["tinystories", "fineweb-edu"]
    )
    prepare.add_argument("--tokens", type=int, default=20_000_000, help="target token count")
    prepare.add_argument("--out", default="python/data", help="output directory")
    prepare.add_argument(
        "--synthetic",
        action="store_true",
        help="skip the download and generate the deterministic synthetic corpus",
    )

    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)

    if args.command == "verify":
        try:
            _require_torch()
            from .verify import DEFAULT_MAX_FORWARD_BYTES, DEFAULT_PHASE_TIMEOUT, verify_model

            report = verify_model(
                args.model,
                batch=args.batch,
                seq=args.seq,
                class_name=args.class_name,
                max_forward_bytes=(
                    args.max_forward_bytes
                    if args.max_forward_bytes is not None
                    else DEFAULT_MAX_FORWARD_BYTES
                ),
                skip_export=args.no_export,
                skip_flops=args.no_flops,
                phase_timeout=(
                    args.phase_timeout if args.phase_timeout is not None else DEFAULT_PHASE_TIMEOUT
                ),
                progress=_progress,
            )
            report["command"] = "verify"
            _progress(
                f"params {report['params']:,} "
                f"({'matches' if report['matches'] else 'DIFFERS FROM'} design)"
            )
            return _emit(report)
        except Exception as exc:  # noqa: BLE001 - always emit parseable JSON
            return _emit(_fail(exc, "verify"))

    if args.command == "smoke-train":
        try:
            _require_torch()
            from .smoke_train import smoke_train

            summary = smoke_train(
                args.model,
                steps=args.steps,
                seq=args.seq,
                batch=args.batch,
                lr=args.lr,
                out=args.out,
                data_dir=args.data,
                class_name=args.class_name,
                seed=args.seed,
                log_every=args.log_every,
                device=args.device,
                compile_model=args.compile,
                weight_decay=args.weight_decay,
                init=args.init,
                progress=_progress,
            )
            summary["command"] = "smoke-train"
            _progress(
                f"done: {summary['steps']} steps, loss {summary['initial_loss']:.4f} -> "
                f"{summary['final_loss']:.4f}, {summary['tokens_per_second']:,.0f} tok/s"
            )
            return _emit(summary)
        except Exception as exc:  # noqa: BLE001
            return _emit(_fail(exc, "smoke-train"))

    if args.command == "trace":
        try:
            _require_torch()
            from pathlib import Path

            from .trace import trace_model

            result = trace_model(
                args.model,
                task=args.task,
                seed=args.seed,
                max_steps=args.max_steps,
                batch=args.batch,
                lr=args.lr,
                tokens=[int(c) for c in args.input.split(",")] if args.input else None,
                positions=args.positions,
                max_params=args.max_params,
                progress=_progress,
            )
            out = Path(args.out)
            out.parent.mkdir(parents=True, exist_ok=True)
            # Compact: the file is mostly base64, and indenting it buys nothing.
            out.write_text(json.dumps(result, separators=(",", ":")) + "\n", encoding="utf-8")
            checks = result["checks"]
            # A trained trace is only worth showing if the model learnt the task.
            # Attention that could not be checked is left out and said so in
            # `attention_note`; it does not make the rest of the trace wrong.
            ok = result["task"]["name"] == "untrained" or bool(checks["sorted_correctly"])
            what = (
                f"{result['training']['steps']} steps, {result['training']['held_out_accuracy']:.1%} sorted"
                if result["task"]["name"] == "sort"
                else "untrained"
            )
            _progress(
                f"trace: {what}, attention error {checks['attention_max_abs_error']}, "
                f"{out.stat().st_size:,} bytes -> {out}"
            )
            if checks["attention_note"]:
                _progress(f"note: {checks['attention_note']}")
            # stdout carries the summary; the trace itself is in the file.
            summary = {k: v for k, v in result.items() if k not in ("weights", "activations", "attention")}
            return _emit({"ok": ok, "command": "trace", "out": str(out), **summary})
        except Exception as exc:  # noqa: BLE001
            return _emit(_fail(exc, "trace"))

    if args.command == "data" and args.data_command == "prepare":
        try:
            from .data import prepare_data

            manifest = prepare_data(
                dataset=args.dataset,
                tokens=args.tokens,
                out=args.out,
                force_synthetic=args.synthetic,
                progress=_progress,
            )
            manifest["ok"] = True
            manifest["command"] = "data prepare"
            _progress(f"prepared {manifest['tokens']:,} tokens from {manifest['source']}")
            return _emit(manifest)
        except Exception as exc:  # noqa: BLE001
            return _emit(_fail(exc, "data prepare"))

    return _emit({"ok": False, "error": f"unknown command {args.command!r}"})


if __name__ == "__main__":
    raise SystemExit(main())
