"""tiny-gpt2 — generated by TensorCAD.

Do not edit by hand: change the design and regenerate.

Symbols:
    L = 6
    D = 384
    H = 6
    Hkv = 6
    dh = 64
    F = 1536
    V = 50257
    Tmax = 512

Parameters: 30,142,848
"""

import torch
import torch.nn as nn
import torch.nn.functional as F


class GqaAttention(nn.Module):
    """gqa_attention: d_model=384, heads=6, kv_heads=6, head_dim=64, bias=true, causal=true, window=0, qk_norm=false, flash=true"""

    def __init__(self):
        super().__init__()
        self.q_proj = nn.Linear(384, 384, bias=True)
        self.k_proj = nn.Linear(384, 384, bias=True)
        self.v_proj = nn.Linear(384, 384, bias=True)
        self.o_proj = nn.Linear(384, 384, bias=True)

    def forward(self, x):
        q_proj_y = self.q_proj(x)
        k_proj_y = self.k_proj(x)
        v_proj_y = self.v_proj(x)
        B, T, _d2 = q_proj_y.shape
        q_heads_y = q_proj_y.view(B, T, 6, 64).permute(0, 2, 1, 3)
        B, T, _d2 = k_proj_y.shape
        k_heads_y = k_proj_y.view(B, T, 6, 64).permute(0, 2, 1, 3)
        B, T, _d2 = v_proj_y.shape
        v_heads_y = v_proj_y.view(B, T, 6, 64).permute(0, 2, 1, 3)
        attn_y = F.scaled_dot_product_attention(q_heads_y, k_heads_y, v_heads_y, is_causal=True)
        B, _d1, T, _d3 = attn_y.shape
        o_merge_y = attn_y.permute(0, 2, 1, 3).reshape(B, T, 384)
        o_proj_y = self.o_proj(o_merge_y)
        return o_proj_y

class DenseMlp(nn.Module):
    """dense_mlp: d_model=384, hidden=1536, act=gelu, bias=true"""

    def __init__(self):
        super().__init__()
        self.up = nn.Linear(384, 1536, bias=True)
        self.down = nn.Linear(1536, 384, bias=True)

    def forward(self, x):
        up_y = self.up(x)
        act_y = F.gelu(up_y)
        down_y = self.down(act_y)
        return down_y

class TransformerBlock(nn.Module):
    """transformer_block: d_model=384, heads=6, kv_heads=6, head_dim=64, ffn_hidden=1536, attention=gqa, q_lora=0, kv_lora=0, nope_dim=0, rope_dim=0, v_dim=0, norm=layernorm, norm_bias=true, post_norm=false, mlp=dense, experts=0, top_k=1, expert_hidden=0, shared_experts=0, router_bias=false, act=gelu, attn_bias=true, mlp_bias=true, qk_norm=false, causal=true, window=0"""

    def __init__(self):
        super().__init__()
        self.norm1 = nn.LayerNorm(384, eps=0.00001, bias=True)
        self.attn = GqaAttention()
        self.norm2 = nn.LayerNorm(384, eps=0.00001, bias=True)
        self.mlp = DenseMlp()

    def forward(self, x):
        norm1_y = self.norm1(x)
        attn_y = self.attn(norm1_y)
        resid1_y = attn_y + x
        norm2_y = self.norm2(resid1_y)
        mlp_y = self.mlp(norm2_y)
        resid2_y = mlp_y + resid1_y
        return resid2_y

class Layer(nn.Module):

    def __init__(self):
        super().__init__()
        self.block = TransformerBlock()

    def forward(self, x):
        block_y = self.block(x)
        return block_y

class TinyGpt2(nn.Module):

    def __init__(self):
        super().__init__()
        self.embed = nn.Embedding(50257, 384)
        self.pos = nn.Embedding(512, 384)
        self.layers = nn.ModuleList([Layer() for _ in range(6)])
        self.final_norm = nn.LayerNorm(384, eps=0.00001, bias=True)
        self.head = nn.Linear(384, 50257, bias=False)
        self.head.weight = self.embed.weight

    def forward(self, ids):
        embed_y = self.embed(ids)
        pos_y = embed_y + self.pos(torch.arange(embed_y.shape[1], device=embed_y.device))
        layers_x = pos_y
        for layer in self.layers:
            layers_x = layer(layers_x)
        final_norm_y = self.final_norm(layers_x)
        head_y = self.head(final_norm_y)
        return head_y


if __name__ == "__main__":
    expected = 30142848
    with torch.device("meta"):
        model = TinyGpt2()
    actual = sum(p.numel() for p in model.parameters())
    print(f"parameters: {actual:,} (design says {expected:,})")
    assert actual == expected, f"parameter count differs: {actual} vs {expected}"
